name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Envinfo
        run: npx envinfo
      - name: npm install, build, and test
        run: |
          yarn
          yarn build
          yarn format-check
          yarn test
        env:
          CI: true
