name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Envinfo
        run: npx envinfo
      - name: Install, build, and test (pnpm)
        run: |
          pnpm install --frozen-lockfile=false
          pnpm build
          pnpm format:check
          pnpm test
        env:
          CI: true
