name: Release Please

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
        if: ${{ steps.release.outputs.release_created }}

      - name: Build
        run: pnpm run build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish
        run: npm publish
        if: ${{ steps.release.outputs.release_created }}
